[package]
name = "mw2md"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Convert MediaWiki markup to Markdown"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["cli", "mediawiki", "markdown", "conversion"]
categories = ["command-line-utilities", "encoding"]
publish.workspace = true

[lints]
workspace = true

[workspace]
resolver = "3"
members = ["mw-fetch", "mw-normalize", "mw-convert"]
default-members = ["mw-fetch", "mw-normalize", "mw-convert"]

[workspace.package]
version = "0.1.0"
authors = ["Dreaght <dreaght@icloud.com>"]
edition = "2024"
rust-version = "1.85"
repository = "https://github.com/Dreaght/mw2md"
license = "MIT"
publish = false

[workspace.lints.rust]
warnings = { level = "deny", priority = -1 }
future-incompatible = { level = "deny", priority = -1 }
let-underscore = { level = "deny", priority = -1 }
nonstandard-style = { level = "deny", priority = -1 }
refining-impl-trait = { level = "deny", priority = -1 }
unknown-or-malformed-diagnostic-attributes = { level = "deny", priority = -1 }
unused = { level = "deny", priority = -1 }

unsafe_code = "forbid"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
pedantic = { level = "deny", priority = -1 }
restriction = { level = "deny", priority = -1 }
nursery = { level = "deny", priority = -1 }
cargo = { level = "deny", priority = -1 }
blanket_clippy_restriction_lints = "allow"

[workspace.lints.rustdoc]
all = { level = "deny", priority = -1 }
